apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-clone-ingress
  namespace: netflix
spec:
  rules:
    - host: netflix.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-clone-svc
                port:
                  number: 80
