apiVersion: v1
kind: Secret
metadata:
  name: netflix-api-secret
  namespace: netflix
type: Opaque
data:
  API_URL: aHR0cHM6Ly9hcGkudGhlbW92aWVkYi5vcmcvMw==
  API_KEY: NmVkMmI5YTY1MTAyOGRjZDQzMDU0ZmM2NTM3OGU5OTM=
